# Generated by Django 5.2.7 on 2025-10-22 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название курса"),
                ),
                ("description", models.TextField(verbose_name="Описание курса")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"profile__role": "student"},
                        related_name="enrolled_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студенты",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        limit_choices_to={"profile__role": "teacher"},
                        related_name="teaching_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Преподаватели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                ("due_date", models.DateTimeField(verbose_name="Срок сдачи")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="assignments.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Домашнее задание",
                "verbose_name_plural": "Домашние задания",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Студент"), ("teacher", "Преподаватель")],
                        default="student",
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solution_file",
                    models.FileField(
                        upload_to="submissions/", verbose_name="Файл с решением"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(blank=True, null=True, verbose_name="Оценка"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Отзыв преподавателя"),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.homework",
                        verbose_name="Домашнее задание",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправка работы",
                "verbose_name_plural": "Отправки работ",
                "ordering": ["-submitted_at"],
                "unique_together": {("homework", "student")},
            },
        ),
    ]
