# Generated by Django 5.2.7 on 2025-10-22 14:16

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="solution_file",
            field=models.FileField(
                upload_to="submissions/",
                validators=[assignments.models.validate_file_size, assignments.models.validate_file_extension],
                verbose_name="Файл с решением",
            ),
        ),
    ]
