# Generated by Django 5.2.7 on 2025-10-22 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_alter_submission_solution_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnrollmentRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "На рассмотрении"), ("approved", "Одобрена"), ("rejected", "Отклонена")],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Опциональное сообщение преподавателю", verbose_name="Сообщение от студента"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата подачи")),
                ("processed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата обработки")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_requests",
                        to="assignments.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обработал",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на курс",
                "verbose_name_plural": "Заявки на курсы",
                "ordering": ["-created_at"],
                "unique_together": {("course", "student")},
            },
        ),
    ]
